# ===== CONTROLLER BOT =====
BOT_TOKEN = "PASTE_BOTFATHER_TOKEN"
CONTROL_GROUP_ID = -1001234567890   # control group id

# ===== USERBOT =====
API_ID = 123456
API_HASH = "PASTE_API_HASH"
SESSION_NAME = "vcfighter"

DEFAULT_VOLUME = 1.0
